# Generated by Django 4.2.1 on 2023-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='hui', upload_to='pics'),
            preserve_default=False,
        ),
    ]
